language: python
python: 3.6

matrix:
  include:
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.4"
    env: TOXENV=py34
  - python: "2.7"
    env: TOXENV=py27
  - python: "pypy"
    env: "TOXENV=pypy"

install: pip install -U tox

script: tox -e ${TOXENV}

after_success:
    - coveralls
